datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:3254/refl-task
  username: postgres
  password: postgres
  maximumPoolSize: 20
  minimumPoolSize: 5
  maxOpenPreparedStatements: 10

cache:
  algorithm-type: LFU
  capacity: 13
