datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:3254/refl-task
  username: postgres
  password: postgres
  init-scripts: /schema.sql,/data.sql
  init-tables-with-data: true
cache:
  algorithm-type: by.kihtenkoolga.cache.handler.impl.LRUCacheHandler
  capacity: 13
  cache-field: id
